// Copyright 2024 Bloomberg Finance L.P.
// Distributed under the terms of the MIT license.

namespace Sable.Cli;

public static class Templates
{
    public const string TransactionTemplate = @"
BEGIN;
{{Script}}
COMMIT;
";
    public const string IdempotentMigrationScriptTemplate = @"
DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM  {{DatabaseSchemaName}}.__sable_migrations WHERE migration_id = '{{MigrationId}}') THEN

        RAISE NOTICE 'Running migration with Id = {{MigrationId}}';

        {{Script}}
        
        INSERT INTO {{DatabaseSchemaName}}.__sable_migrations (migration_id, backfilled)
        VALUES ('{{MigrationId}}', '{{Backfilled}}');
    END IF;
END $$;
";
    public const string IdempotentMigrationRecordInsertionTemplate = @"
DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM  {{DatabaseSchemaName}}.__sable_migrations WHERE migration_id = '{{MigrationId}}') THEN

        RAISE NOTICE 'Inserting record for migration with Id = {{MigrationId}}';

        INSERT INTO {{DatabaseSchemaName}}.__sable_migrations (migration_id, backfilled)
        VALUES ('{{MigrationId}}', '{{Backfilled}}');
    END IF;
END $$;
";
    public const string InfrastructureSetupTemplate = @"
-- Generated by Sable on {{Date}}
-- Sable NoIdempotenceWrapper

CREATE SCHEMA IF NOT EXISTS {{DatabaseSchemaName}};

CREATE TABLE IF NOT EXISTS {{DatabaseSchemaName}}.__sable_migrations (
    migration_id        character varying(150)      NOT NULL,
    date_applied        timestamp without time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    backfilled          boolean                     NOT NULL DEFAULT false,
CONSTRAINT pkey___sable_migrations_migration_id PRIMARY KEY (migration_id)
);
";

    public const string NoIdempotenceBlockTemplate = @"
{{Script}}

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM  {{DatabaseSchemaName}}.__sable_migrations WHERE migration_id = '{{MigrationId}}') THEN

        RAISE NOTICE 'Inserting record for migration with Id = {{MigrationId}}';

        INSERT INTO {{DatabaseSchemaName}}.__sable_migrations (migration_id, backfilled)
        VALUES ('{{MigrationId}}', '0');
    END IF;
END $$;
";

    public const string BackfillScriptTemplate = @"
-- Generated by Sable on {{Date}}

BEGIN;
CREATE TABLE IF NOT EXISTS {{DatabaseSchemaName}}.__sable_migrations (
    migration_id        character varying(150)      NOT NULL,
    date_applied        timestamp without time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    backfilled          boolean                     NOT NULL DEFAULT false,
CONSTRAINT pkey___sable_migrations_migration_id PRIMARY KEY (migration_id)
);
{{ for migrationInsertionScript in MigrationInsertionScripts }}

{{migrationInsertionScript}}
{{ end }}
COMMIT;
";
}
