
-- Generated by Sable on 1/30/2024 3:00:18 AM
-- Sable NoIdempotenceWrapper

CREATE SCHEMA IF NOT EXISTS books;

CREATE TABLE IF NOT EXISTS books.__sable_migrations (
    migration_id        character varying(150)      NOT NULL,
    date_applied        timestamp without time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    backfilled          boolean                     NOT NULL DEFAULT false,
CONSTRAINT pkey___sable_migrations_migration_id PRIMARY KEY (migration_id)
);
